task_recherche:
  description: >
    Effectue une recherche approfondie et précise sur le sujet : {topic}.
    Trouve des informations fiables, actuelles et pertinentes, incluant des sources ou données marquantes si possible.
  expected_output: >
    Une liste claire de 10 à 15 points clés sur {topic}, incluant toute information utile trouvée en ligne.
  agent: agent_recherche

task_redaction:
  description: >
    Rédige un rapport structuré et fluide à partir des résultats de recherche précédents.
    Organise les idées en sections logiques et assure-toi que le contenu soit clair et complet.
  expected_output: >
    Un rapport complet présentant les principaux sujets, chacun accompagné d'une section d'information complète.
    Formaté en Markdown sans '```'
  agent: agent_redaction

task_revision:
  description: >
    Relis et améliore le contenu du rapport.
    Corrige les fautes, clarifie les formulations, et assure-toi de la cohérence et de la fluidité.
  expected_output: >
    Une version finale propre du rapport Markdown, prête à être exportée.
  agent: agent_reviseur
